version: '3.8'

services:
  # DB
  mongo:
    image: mongo:6-jammy
    # image: mongo:5.0.2
    container_name: mongodatabase
    restart: always
    env_file: ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    #   - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - node-network
    expose:
      - $MONGODB_LOCAL_PORT
    volumes:
      - db:/data/db

  # API
  techforum-api:
    build: ../backend_express
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_DOCKER_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_LOCAL_PORT
      - COOKIE_SECRET=$API_COOKIE_SECRET
      - SECRET_KEY=$API_SECRET_KEY
      - CLOUDYNARY_CONFIG_CLOUD_NAME=$API_CLOUDYNARY_CONFIG_CLOUD_NAME
      - CLOUDYNARY_CONFIG_API_KEY=$API_CLOUDYNARY_CONFIG_API_KEY
      - CLOUDYNARY_CONFIG_API_SECRET=$API_CLOUDYNARY_CONFIG_API_SECRET
      - MEGA_CONFIG_EMAIL=$API_MEGA_CONFIG_EMAIL
      - MEGA_CONFIG_PASSWORD=$API_MEGA_CONFIG_PASSWORD
      - PORT=$NODE_DOCKER_PORT
      - DB_PASSWORD=$API_DB_PASSWORD
    stdin_open: true
    tty: true
    networks:
      - node-network
    links:
      - mongo

  # FE
  techforum-fe:
    build: ../frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 5000:3000
    # environment:
    #   - NEXT_PUBLIC_BACKEND_URL=techforum-api
    networks:
      - node-network

volumes:
  db:
networks:
  node-network:
    driver: bridge